name: TownyPolitical
version: 0.3_Alpha # 将由 Gradle processResources 替换为项目版本
main: top.chickenshout.townypolitical.TownyPolitical
api-version: 1.19 # 兼容 Paper 1.19.x
author: chickenshout # 替换为你的名字
description: A political plugin for the Towny servers , incorporates political systems, parties, and elections to enhance the gaming experience.

# 插件依赖
# softdepend 意味着插件会在这些插件之后加载（如果它们存在），但没有它们也能（尝试）加载
# depend 意味着这些插件必须存在，否则本插件无法加载
depend:
  - Vault
  - Towny
# softdepend: # 如果某些经济插件是可选的，或者 SiegeWar 是可选的
#   - TheNewEconomy # 你指定了 TheNewEconomy，所以它更像硬依赖，但通过Vault抽象
#   - SiegeWar # 如果 SiegeWar 不是核心功能强制的

# 命令定义
commands:
  townypolitical:
    description: Main command for TownyPolitical.
    usage: /<command> <subcommand> [args...]
    aliases: [tp, tpol, political]
    permission: townypolitical.command.base # 基础使用权限
  tparty: # 政党命令的快捷方式，可以指向同一个CommandExecutor
    description: Alias for TownyPolitical party commands.
    usage: /<command> <subcommand> [args...]
    aliases: [party]
    permission: townypolitical.command.party.base

# 权限定义 (示例，你需要根据功能细化)
permissions:
  townypolitical.*: # Wildcard for all plugin permissions (typically for admins)
    description: Grants access to all TownyPolitical features and commands.
    default: op
    children:
      townypolitical.admin: true

  townypolitical.admin: # Specific admin permission node
    description: Grants administrative access to TownyPolitical (e.g., reload, manage elections).
    default: op
    children:
      townypolitical.command.reload: true
      townypolitical.election.manage: true
      townypolitical.party.manage_applicants_any: true # Allows admin to see any party's applicants
      townypolitical.bill.manage: true # (If bills were included)
      townypolitical.admin.notifications: true # For receiving admin-specific alerts

  townypolitical.command.base:
    description: Allows basic usage of /townypolitical (like help and info).
    default: true

  townypolitical.command.reload:
    description: Allows usage of /townypolitical reload.
    default: op

  # --- Party Permissions ---
  townypolitical.party.base: # Base for /tp party ... or /tparty ...
    description: Allows access to basic party commands.
    default: true
    children:
      townypolitical.party.info: true
      townypolitical.party.list: true
      townypolitical.party.apply: true
      townypolitical.party.leave: true

  townypolitical.party.create:
    description: Allows players to create a new party.
    default: true # Or set to 'op' or a specific group if creation is restricted
  townypolitical.party.disband:
    description: Allows party leaders to disband their own party. (Logic also checks leader status)
    default: true
  townypolitical.party.info:
    description: Allows players to view party information.
    default: true
  townypolitical.party.list:
    description: Allows players to list all parties.
    default: true
  townypolitical.party.apply:
    description: Allows players to apply to join a party.
    default: true
  townypolitical.party.leave:
    description: Allows players to leave their party.
    default: true
  townypolitical.party.manage_applications: # For accept/reject within own party by admin/leader
    description: Allows party admins/leaders to accept or reject applications for their party.
    default: true
  townypolitical.party.manage_applicants_any: # Admin permission (child of townypolitical.admin)
    description: Allows viewing applicants of any party (for /tp party info <any_party>).
    default: op
  townypolitical.party.invite: # Direct add member
    description: Allows party admins/leaders to directly add members to their party.
    default: true
  townypolitical.party.kick:
    description: Allows party admins/leaders to kick members from their party.
    default: true
  townypolitical.party.promote:
    description: Allows party leaders to promote members in their party.
    default: true
  townypolitical.party.demote:
    description: Allows party leaders to demote members in their party.
    default: true
  townypolitical.party.rename:
    description: Allows party leaders to rename their party.
    default: true
  townypolitical.party.setleader: # Transfer leadership
    description: Allows party leaders to transfer leadership of their party.
    default: true
  townypolitical.party.setmps: # <--- 新增
    description: Allows party leaders to set their party's MPs in a nation's parliament. # <--- 新增
    default: true # 逻辑会检查是否为领袖 # <--- 新增
  townypolitical.party.addmp: # <--- 新增
    description: Allows party leaders to add an MP for their party in a nation.
    default: true
  townypolitical.party.removemp: # <--- 新增
    description: Allows party leaders to remove an MP of their party in a nation.
    default: true
  townypolitical.party.listmps: # <--- 新增
    description: Allows players to list MPs in a nation's parliament.
    default: true

  # --- Nation & Government Permissions ---
  townypolitical.nation.setgovernment:
    description: Allows nation leaders (Towny King) to change their nation's government type.
    default: op # Or true, command logic still verifies King status
  townypolitical.nation.governmentinfo:
    description: Allows players to view nation government information and list available types.
    default: true
  townypolitical.nation.setmonarch:
    description: Allows nation leaders (Towny King) to set/remove a titular monarch in Constitutional Monarchies.
    default: op # Or true
  townypolitical.nation.appointpremier:
    description: Allows nation Presidents (Towny King) to appoint/remove a Prime Minister in Semi-Presidential Republics.
    default: op # Or true
  townypolitical.nation.parliamentinfo:
    description: Allows players to view nation parliament seat distribution.
    default: true

  # --- Election Permissions ---
  townypolitical.election.info:
    description: Allows players to view election information, candidates, and results.
    default: true
  townypolitical.election.registercandidate:
    description: Allows eligible players to register as a candidate in elections.
    default: true
  townypolitical.election.vote:
    description: Allows eligible players to vote in elections.
    default: true
  townypolitical.election.manage: # For admin commands like start/stop election
    description: Allows administrators to manage elections.
    default: op

  # --- Bill Permissions ---
  townypolitical.bill.base: # 基础法案命令权限
    description: Allows access to basic bill commands.
    default: true
    children:
      townypolitical.bill.list: true
      townypolitical.bill.info: true

  townypolitical.bill.propose:
    description: Allows eligible players/leaders to propose bills.
    default: true # 实际能否提案由 BillManager 中的逻辑决定
  townypolitical.bill.list:
    description: Allows players to list bills.
    default: true
  townypolitical.bill.info:
    description: Allows players to view bill details.
    default: true
  townypolitical.bill.vote:
    description: Allows eligible players/MPs to vote on bills.
    default: true # 实际能否投票由 BillManager 中的逻辑决定